# Generated by Django 2.0.6 on 2018-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=32)),
                ('settingName', models.CharField(max_length=32)),
                ('settingValue', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
