# Generated by Django 2.0.6 on 2018-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monzohosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='settingValue',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
