# Generated by Django 2.0.6 on 2018-06-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monzohosting', '0002_auto_20180612_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='webhookReceivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=32)),
                ('webhookType', models.CharField(max_length=32)),
                ('canReceive', models.BooleanField(default=False)),
            ],
        ),
    ]
