# Generated by Django 2.0.6 on 2018-06-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monzohosting', '0003_webhookreceivers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
